### ISSUE TITLE
Dataset is missing 

### ISSUE THREAD

**Issue by anas-ansri** [MonitSharma/Learn-Quantum-Machine-Learning#1]
When I was working on "Classifying existence of Galaxy using Quantum Machine Learning" I realized that 
data/datasets are missing from the repository. Is there any way where we can download data or could you please add it?

**Comment by MonitSharma** [comment]
Hi Anas, check the other repository out. Here's the link: [QML in NISQ era ](https://github.com/MonitSharma/Quantum-Machine-Learning-on-Near-Term-Quantum-Devices/tree/main/Galaxy%20Detection%20using%20Quantum%20Machine%20Learning).
